environment: development
coordinator: 
  enabled: true
  fullName: "ceremony-coordinator-{{$.Values.environment}}"
  image: 
    repo: "us.gcr.io/celo-testnet"
    image: coordinator-service
    tag: test
    full: "{{$.Values.coordinator.image.repo}}/{{$.Values.coordinator.image.image}}:{{$.Values.coordinator.image.tag}}"
  authType: celo
  configPath: ceremony/empty.json
  apiURL: 'http://{{ tpl $.Values.coordinator.fullName . }}:8080'
  storageType: azure
  storageAccount: "ceremonykubernetes"
  azureAccessKey: ""
  azureLoadBalancerIP: ""
  azureResourceGroup: ""
  container: chunks
  initialVerifier: ""
