environment: development

coordinator: 
  enabled: true
  fullName: "ceremony-coordinator-{{$.Values.environment}}"
  image: 
    repo: "us.gcr.io/celo-testnet"
    image: coordinator-service
    tag: test
    full: "{{$.Values.coordinator.image.repo}}/{{$.Values.coordinator.image.image}}:{{$.Values.coordinator.image.tag}}"
  authType: celo
  configPath: ceremony/empty.json
  apiURL: 'http://{{ $.Values.coordinator.fullName }}:8080'
  storageType: azure
  storageAccount: "ceremonykubernetes"
  azureAccessKey: "nHx8SjML9BOWD6n3jeGTB6ARvihNGfIyi/Oadg3d07OXglxb6TfSqIpt0i/kOiosV6PmzY8MvNPTrMLpqQnPDw=="
  container: chunks
  initialVerifier: 0x07dfadb3483c474fc0913a232cc3a06483d17060
