environment: development
coordinator: 
  enabled: true
  fullName: "nimiq-coordinator-{{$.Values.environment}}"
  image: 
    repo: "us.gcr.io/nimiq-testnet"
    image: coordinator-service
    tag: test
    full: "{{$.Values.coordinator.image.repo}}/{{$.Values.coordinator.image.image}}:{{$.Values.coordinator.image.tag}}"
  authType: nimiq
  configPath: ceremony/empty.json
  apiURL: 'http://{{ tpl $.Values.coordinator.fullName . }}:8080'
  storageType: azure
  storageAccount: "ceremonykubernetes"
  azureAccessKey: ""
  azureLoadBalancerIP: ""
  azureResourceGroup: ""
  container: chunks
  initialVerifierPublicKeys: ""

participant: 
  numParticipants: 1
  enabled: false
  fullName: "nimiq-verifier-{{$.Values.environment}}"
  image: 
    repo: "us.gcr.io/nimiq-testnet"
    image: snark-ceremony-operator
    tag: test
    full: "{{$.Values.participant.image.repo}}/{{$.Values.participant.image.image}}:{{$.Values.participant.image.tag}}"
  participationMode: verify #contribute 
  nimiqKeys: 
    - key: ""
      password: ""
  coordinatorUri: http://{{ tpl $.Values.coordinator.fullname . }}:8080

monitor: 
  enabled: false
  fullName: "nimiq-monitor-{{$.Values.environment}}"
  image: 
    repo: "us.gcr.io/nimiq-testnet"
    image: snark-ceremony-operator
    tag: test
    full: "{{$.Values.monitor.image.repo}}/{{$.Values.monitor.image.image}}:{{$.Values.monitor.image.tag}}"
  pollingInterval: 1 # polling interval in minutes
  coordinatorUri: http://{{ tpl $.Values.coordinator.fullname . }}:8080
  numReplicas: 1