apiVersion: v1
kind: Secret
metadata:
  name: new-challenge
type: Opaque
data:
  seed: OTJBQ0I4RDhBNTk0MUVDMkQ3RjgxQzUwMTU3ODZCNTYK
  key: MHhlODExOTU2MmViM2QwNzFlMTQ2YWUyZDJjNzMyZDIyNGRhZmU2ZTAzMjM4OWNmMTFkYzY4MjlmZTQ5YzcwYjQz
