{{ if $.Values.contributor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.coordinator.fullName }}
  labels:
    app: {{ $.Values.coordinator.fullName }}
spec:
  ports:
    - port: 8080
      name: coordinator-web
  selector:
    app: {{ $.Values.coordinator.fullName }}
{{ end }}