{{ if $.Values.contributor.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.coordinator.fullName }}
  labels:
    app: {{ $.Values.coordinator.fullName }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ end }}