{{ if $.Values.coordinator.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if $.Values.coordinator.azureResourceGroup }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ $.Values.coordinator.azureResourceGroup }}
  {{- end }}
  name: {{ tpl $.Values.coordinator.fullName . }}
  labels:
    app: {{ tpl $.Values.coordinator.fullName . }}
spec:
  type: LoadBalancer
  {{- if $.Values.coordinator.azureLoadBalancerIP }}
  loadBalancerIP: {{ $.Values.coordinator.azureLoadBalancerIP }}
  {{- end }}
  ports:
    - port: 8080
      name: coordinator-web
  selector:
    app: {{ tpl $.Values.coordinator.fullName . }}
{{ end }}