{{ if $.Values.coordinator.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator-service
  serviceName: coordinator-service
  template:
    metadata:
      labels:
        app: coordinator-service
    spec:
      containers:
        - image: coordinator-service:test
          name: coordinator-service
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: coordinator-service
          env:
            - name: COORDINATOR_DB_FILE
              value: /db/db.json
            - name: COORDINATOR_DISK_CHUNK_STORAGE_DIRECTORY
              value: /db
          volumeMounts:
            - name: db
              mountPath: /db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: coordinator-service
{{ end }}