{{ if $.Values.coordinator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $.Values.coordinator.fullName . }}-secret
type: Opaque
data:
  azure_key: {{ $.Values.coordinator.azureAccessKey }}
{{ end }}