{{ if $.Values.coordinator.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl $.Values.coordinator.fullName . }}-pvc
  labels:
    app: {{ tpl $.Values.coordinator.fullName . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ end }}