{{ if $.Values.monitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl $.Values.monitor.fullName . }}-configmap
data:
    COORDINATOR_URI: {{ tpl $.Values.monitor.coordinatorUri . }}
    POLLING_INTERVAL: {{ $.Values.monitor.pollingInterval | quote }}
{{ end }}