{{if $.Values.participant.enabled }}
{{ if eq $.Values.participant.participationMode "verify" }}
{{- range $index, $keyPair := .Values.participant.plumoKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $.Values.participant.fullName $ }}-secret-{{ $index }}
type: Opaque
stringData:
  plumo.keys: |
    {{ $keyPair.key }}
  password: {{ $keyPair.password | quote }}
{{ end }}
{{ end }}
{{ end }}