{{if $.Values.participant.enabled }}
{{ if eq $.Values.participant.participationMode "verify" }}
{{- range $index := until (int .Values.participant.numParticipants) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $.Values.participant.fullName $ }}-secret-{{ $index }}
type: Opaque
stringData:
  {{- with index $.Values.participant.plumoKeys $index }}
  plumo.keys: |
    {{ .key }}
  password: {{ .password }}
  {{- end }}
{{ end }}
{{ end }}
{{ end }}