name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node 12
    defaults:
      run:
        working-directory: coordinator-client
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: npm run test
