apiVersion: batch/v1
kind: Job
metadata:
  name: verifier
spec:
  template:
    metadata:
      labels:
        app: verifier
    spec:
      containers:
        - image: coordinator-client:test
          name: verifier
          envFrom:
            - configMapRef:
                name: verifier
          volumeMounts:
            - name: verifier
              mountPath: "/mnt/secrets"
              readOnly: true
          command: ["npm"]
          args: ["start", "--", "verify"]
      restartPolicy: Never
      volumes:
        - name: verifier
          secret:
            secretName: verifier
