name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Node 12
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [coordinator-client, coordinator-service]
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: npm run test
  test-e2e:
    runs-on: ubuntu-latest
    name: E2E
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - run: node e2e/run-e2e-suite.js
